- .circleci/config.yml
NO JIRA
This PR fixes the master build and release process on the CI, currently it doesn't run the jobs as the filter is too restrictive.
> NOJIRA: Fix no run CI build step on Master merge

- .circleci/config.yml
Let's see if this works. It should be enough as the `semantic_release` error is:
```
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.
```
> fix(): use gha-token-generator and set GITHUB_TOKEN env var

- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java
- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAInterstitialAd.java
- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoActivity.java
- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoAd.java
Adding debug logs for:
- adLoaded
- adShown
- adClicked
- adEnded
- adClosed
Debug logs can now be seen in Logcat, and can easily be found by keeping a filter on for `Event callback: `.
Video below showing debug logs being registered and easily seen for the above callbacks.
https://user-images.githubusercontent.com/48458132/152332378-b6dee0f5-41da-4c4f-b136-2be1805b9419.mov
> Aag 1591 callback logs

- README.md
The semantic release information is useful to be written in multiple repos - by storing it in one place in Confluence, we can just link it into multiple repos instead.
> Update README with link-out to Confluence page

- CHANGELOG.md
This is for visibility to our Publishers, as the VPAID JS Bridge work was done in this version but hidden in the commits list instead
> Update Changelog to include VPAID completion

- saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityBannerAd.java
- saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityInterstitialAd.java
- saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityVideoAd.java
- superawesome-base/src/test/java/tv/superawesome/lib/sasession/defines/SAConfigurationTest.java
This PR fixes an issue where Ads wouldn't load on Unity Android. This was caused by using the `fromOrdinal` method which relies on the index position in the `SAConfiguration` of `Production` or `Staging` but the `SAConfiguration` in the Android SDK has another case `Dev` which was causing a mismatch. It seems to be safer overall to use the `fromValue` method which matches on the enum `rawValue` rather than the index position.
> fix(): fix for missing ads on Unity Android

- superawesome-base/src/main/java/tv/superawesome/lib/saclosewarning/SACloseWarning.java
- superawesome-base/src/main/java/tv/superawesome/lib/saparentalgate/SAParentalGate.java
- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoActivity.java
fix(): Video Ad crashes when the Warning dialog is accessed even after the activity is closed
Main cause: When the system decides to destroy activity in the background and if the close warning dialog is present, then it causes this kind of crashes. 
P.s.: Need to release a new unity version as well.
> fix(): Video Ad crashes when the Warning dialog is accessed

- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/components/AdQueryMaker.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/components/TimeProvider.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/di/CommonModule.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/AdModels.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/banner/BannerView.kt
- superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/components/AdQueryMakerTest.kt
- superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/components/TimeProviderTest.kt
Adding the timestamp to the requests in the new codebase. 
Note: Java 8+ `Clock` is not preferred as a source for`TimeProvider` as it is only available API 26 and above. To be able to use it below API 26 we need to enable `coreLibraryDesugaring` which increases the size of our library.
Another alternative is `Calendar.getInstance(). getTimeInMillis()` This could be used but I wanted to avoid creating the `Calendar` object each time. However, if we think this can be better, then I can update the code.
> chore(): add timestamp to the requests

- superawesome-common/build.gradle
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/AdModels.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/Constants.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/CreativeModels.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/banner/BannerView.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/common/AdController.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/common/Config.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/managed/ManagedBannerView.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/VideoActivity.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/VideoComponentFactory.kt
- superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/components/AdResponseTest.kt
This PR hides the safe ad logo for KSF Ads and fixes a crashing issue with the chucker library for API 31 and above in the common `build.gradle`.
I had to make some changes to `VideoActivity` since the `currentAdResponse` is not retrieved from the `AdStore` until `play`. The changes are similar to how the `WebView` is added in `BannerView` without the removal since the `VideoActivity` replaces the `IVideoPlayerControllerView` itself and it's destroyed on close. I've also matched the safe ad logo padding to the `BannerView` padding but we may want to tweak the padding / positioning for both for styling reasons.
> chore(): configuration for hiding the safe ad logo for KSF ads

- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/extensions/PropertiesExtensions.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/QueryAdditionalOptions.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/network/retrofit/RetrofitAdDataSource.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/sdk/AwesomeAdsSdk.kt
- superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/components/AdQueryMakerTest.kt
This PR adds a new initialiser for the refactored SDK that allows a map of additional options to be passed that are added to each request query.
Here is an example url outputted when using the initialiser with an options map (`testKey` and `testValue` are set from the options map):
`https://ads.superawesome.tv/v2/ad/88406?test=false&sdkVersion=android_8.3.6&rnd=1389563&bundle=tv.superawesome.demoapp&name=SASDK%2B-%2BAndroid&dauid=611023259&ct=Wifi&lang=en_US&device=phone&pos=7&skip=1&playbackmethod=5&startdelay=0&instl=1&w=1080&h=2160&timestamp=1661940061004&testKey=testValue`
> chore(): Added additional query options set at SDK init

- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoActivity.java
This PR removes the `listenerRef` in the `SAVideoActivity` when the video is either completed or closed to prevent duplicate events being sent. Please see the attached video for the manual testing:
https://user-images.githubusercontent.com/30452349/188128681-4723cb1b-6990-4614-be25-c4edad7e5fcb.mov
> chore(): Prevent duplicate adClosed and adEnded events

- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVersion.java
- superawesome-base/src/test/java/tv/superawesome/lib/saversion/TestSAVersion.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/components/SdkInfo.kt
- superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/components/SdkInfoTest.kt
This PR adds a method to get the version number only for the legacy and refactored codebases
> chore(): Expose version number

- .circleci/config.yml
- CHANGELOG.md
This PR resets the changelog for `8.3.7`, removes the tags filter for semantic release and the requires block for prep_deploy
> fix(): Remoe tags on semantic release and requires on prep_deploy

- docs/_data/toc.yml
- docs/_docs/bumper-page.md
- docs/_docs/parental-gate.md
This PR updates the documentation for disabling the bumper and the parental gate.
> chore(): Updating the documentation for disabling the parental gate and the bumper

- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoActivity.java
- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/managed/SAManagedAdActivity.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/VideoActivity.kt
This PR prevents apps using the SDK from entering sleep mode when video ads are playing. Device sleep is only prevented whilst the video activities are open, exiting the video screen means sleep mode can occur as normal.
> fix(): This PR prevents the app from going to sleep when playing video ads

- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/common/AdController.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/common/ParentalGate.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/fullscreen/FullScreenActivity.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/managed/ManagedAdActivity.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/managed/ManagedAdView.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/VideoActivity.kt
- superawesome-common/src/main/res/values/strings.xml
[AAG-2796]
This PR fixes the absent Parent Gate on clicking an ad. 
https://user-images.githubusercontent.com/618350/216127528-60f37340-4b43-4acd-a2ec-dce9206c8b45.mov
[AAG-2796]: https://superawesomeltd.atlassian.net/browse/AAG-2796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AAG-2796: Added a check to show the parent gate if needed

- superawesome-common/src/main/AndroidManifest.xml
- superawesomecomposeexample/src/main/java/com/superawesome/composeexample/ComposeApp.kt
[AAG-2795]
This PR adds the missing theme to the SDK manifest that enables the bumper to be displayed correctly.
I have also added other missing themes to the video, interstitial and managed ad activities.
https://user-images.githubusercontent.com/618350/216117128-0466fbf6-6778-4b30-b6dc-40414afc9c0e.mov
[AAG-2795]: https://superawesomeltd.atlassian.net/browse/AAG-2795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AAG-2795: Added missing theme to Bumper

- .circleci/config.yml
NO-JIRA
Updated Android CI machine image following the recommended upgrade in preparation for UI testing
https://circleci.com/developer/images/image/cimg/android
> NO-JIRA: Updated Android CI machine image

- docs/_docs/video-ads.md
None
The method shown in this example in the docs had the wrong name. The name has been changed to `disableSmallClickButton` in the code and this PR updates the docs to match that.
n/a
> Updates method naming on one of the VideoAd methods.

- saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityVideoAd.java
- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/state/CloseButtonState.kt
- superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/state/CloseButtonState.kt
- superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/state/CloseButtonStateTest.kt
[AAG-2881]
Added support for different video close button modes in the unity code, replacing the close enabled boolean with an int for the possible states.
I have also changed the order of the `CloseButtonState` enum to mirror iOS.
From: `Hidden(0), VisibleWithDelay(1), VisibleImmediately(2);`
To: `VisibleWithDelay(0), VisibleImmediately(1), Hidden(2);`
n/a
[AAG-2881]: https://superawesomeltd.atlassian.net/browse/AAG-2881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AAG-2881: Added support for different video close button modes in the unity code

- app/src/main/java/tv/superawesome/demoapp/AdMobActivity.kt
- saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/EventListener.kt
- saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobInterstitialAd.kt
- saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobRewardedAd.kt
- superawesome-base/src/test/java/tv/superawesome/lib/saversion/TestSAVersion.kt
[AAG-2965]
fix(admob): Allow event listener for admob adapter to listen multiple ad loads at the same time
[AAG-2965]: https://superawesomeltd.atlassian.net/browse/AAG-2965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(admob): Allow event listener to listen multiple ad loads

- superawesome-base/src/main/java/tv/superawesome/sdk/publisher/managed/SAManagedAdActivity.kt
[AASDK-480]
This PR adds the fix for showing the close button on `adEnded` for IV. Tested manually and with the previously added UI test.
n/a
[AASDK-480]: https://superawesomeltd.atlassian.net/browse/AASDK-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(): Showing the close button on adEnded if set to hidden
