SuperAwesomeLTD/sa-mobile-sdk-android

saadmob/src/main/AndroidManifest.xml, samopub/src/main/AndroidManifest.xml, superawesome-base/src/main/AndroidManifest.xml, superawesome-base/src/main/java/tv/superawesome/lib/sasession/session/SASession.java, superawesome-base/src/main/java/tv/superawesome/lib/sautils/SAUtils.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAInterstitialAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVersion.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoAd.java
Set the plugin name on the sdk parameter e.g
`android_7.2.7_admob`
or
`android_7.2.7_mopub`
https://jira.superawesome.tv/browse/AAG-96
=> Set the plugin name on the sdk parameter

superawesome-base/src/main/java/tv/superawesome/lib/sawebplayer/SAWebPlayer.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java
Custom events still fire after ad is closed
https://jira.superawesome.tv/browse/AAG-168
=> Stopping webview after it is being closed

app/build.gradle, bintray.gradle, build.gradle, docs/_docs/add-sdk.md, docs/_docs/admob-integration.md, docs/_docs/mopub-integration.md, saadmob/build.gradle, saair/build.gradle, samoat/build.gradle, samopub/build.gradle, saunity/build.gradle, superawesome-base/build.gradle, superawesome/build.gradle
-Removed deprecated `com.github.dcendents:android-maven-gradle-plugin` plugin
-Updated publishing to the central location into `bintray.gradle`
-Updated all `build.gradle` files in each project
=> Update gradle files

.gitignore, app/src/main/java/tv/superawesome/demoapp/MainActivity.java, samoat/src/main/java/tv/superawesome/plugins/publisher/moat/SAMoatEvents.java, superawesome-base/src/main/java/tv/superawesome/lib/saevents/SAEvents.java, superawesome-base/src/main/java/tv/superawesome/lib/saevents/SAMoatModule.java, superawesome-base/src/main/java/tv/superawesome/lib/saevents/SAServerModule.java, superawesome-base/src/main/java/tv/superawesome/lib/saevents/events/SAMoatAttemptEvent.java, superawesome-base/src/main/java/tv/superawesome/lib/saevents/events/SAMoatAttemptNoClassEvent.java, superawesome-base/src/main/java/tv/superawesome/lib/saevents/events/SAMoatErrorEvent.java, superawesome-base/src/main/java/tv/superawesome/lib/saevents/events/SAMoatSuccessEvent.java, superawesome-base/src/main/java/tv/superawesome/lib/sawebplayer/SAWebPlayer.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java, superawesome-base/src/test/java/tv/superawesome/lib/saevents/mocks/server/events/MockEventsServer.java
Track moat events to know how many failure/attempt we have
=> Add events for moat

.gitignore, .idea/compiler.xml, .idea/misc.xml, .idea/modules.xml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/tv/superawesome/demoapp/MainActivity.java, app/src/main/java/tv/superawesome/demoapp/NewTestActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_new_test.xml, build.gradle, superawesome-base/build.gradle, superawesome-base/src/main/AndroidManifest.xml, superawesome-base/src/main/java/tv/superawesome/lib/sasession/defines/SAConfiguration.java, superawesome-base/src/main/java/tv/superawesome/lib/sasession/session/SASession.java, superawesome-base/src/main/java/tv/superawesome/lib/sawebplayer/SAWebPlayer.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAInterstitialAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/managed/SAManagedBannerAd.kt, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/managed/SAManagedInterstitialAd.kt
Android SDK to load WebSDK for display ads.
=> feat(): Android SDK to load WebSDK for display ads.

superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/components/AdProcessor.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/components/VastParser.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/VastModels.kt, superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/components/AdProcessorTest.kt, superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/components/VastParserTest.kt, superawesome-common/src/test/resources/mock_vast_response_2.0.xml
- add unit test
- remove unneed vars and mutable lists
- optimise passing
- prevent infinate loop
=> Update Vast passer

.circleci/config.yml
NOJIRA
Disabled unit tests on the Develop branch
=> NOJIRA: Disabled test CI

.circleci/config.yml, build.gradle, local.properties.ci, publish.gradle, saadmob/build.gradle, saair/build.gradle, samoat/build.gradle, samopub/build.gradle, saunity/build.gradle, superawesome-base/build.gradle, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java, superawesome-base/src/test/java/tv/superawesome/lib/ResourceReader.java, superawesome/build.gradle
This PR fixes issues in the maven publish step of the libraries as the source java classes were missing in the published files.
=> NOJIRA: Fixed issues in gradle build scripts

.circleci/config.yml
This PR fixes the filters on the publish jobs of the CI
=> NOJIRA: Amended job filters

.circleci/config.yml
Added entry point for tag workflow.
=> NOJIRA: Adjusted CI config for tag

.circleci/config.yml, fastlane/Fastfile, saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobVideoMediationAdapter.kt
This PR fixes the issues caused by the updates on the Continuous integration repo.
=> NOJIRA: CI Bundler fixes

.circleci/config.yml
Removed the SAAir archive build step from the CI as the module has been removed from the project.
=> NOJIRA: update ci remove saair

.circleci/config.yml
This PR fixes the build step config for Circle CI so that releases can be triggered.
=> NOJIRA: Updated the CI Release config

saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobBannerCustomEvent.java, saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobInterstitialCustomEvent.java, saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobRewardedAd.kt, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityBannerAd.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityInterstitialAd.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityVideoAd.java, superawesome-base/src/main/java/tv/superawesome/lib/sasession/defines/SAConfiguration.java, superawesome-base/src/main/java/tv/superawesome/lib/sautils/SAUtils.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVersion.java, superawesome-base/src/test/java/tv/superawesome/lib/sasession/defines/SAConfigurationTest.java, superawesome-base/src/test/java/tv/superawesome/lib/sautils/aux/TestSAUtils_RandomNumberBetween.java
* add button to show add mob in test activity
* fix broken unit test
* bump version number in SAVersion
* update version number
=> add button to show add mob in test activity (#130)

saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobBannerCustomEvent.java, saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobInterstitialCustomEvent.java, saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobRewardedAd.kt, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityBannerAd.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityInterstitialAd.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityVideoAd.java, superawesome-base/src/main/java/tv/superawesome/lib/sasession/defines/SAConfiguration.java, superawesome-base/src/main/java/tv/superawesome/lib/sautils/SAUtils.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVersion.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoClick.java, superawesome-base/src/test/java/tv/superawesome/lib/sasession/defines/SAConfigurationTest.java, superawesome-base/src/test/java/tv/superawesome/lib/sautils/aux/TestSAUtils_RandomNumberBetween.java
Merging into develop to build Release v8.2.1
=> Develop -> Master for release

app/src/main/java/tv/superawesome/demoapp/MainActivity.java
5 working placements have been created and added.
=> Aag 1590 test app placements

app/src/main/java/tv/superawesome/demoapp/MainActivity.java
Updating placements with safe ad approved KSF campaigns
=> chore(AAG-1842): update test app with safe ad approved campaign ads

superawesome-base/src/main/java/tv/superawesome/lib/samodelspace/saad/SAAd.java
AAG-1843 fix: safe AD logo appearing multiple times when KSF ad is loaded
=> AAG-1843 fix: safe AD logo appearing multiple times when KSF ad is loaded

superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoActivity.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/videoPlayer/VideoPlayerController.kt
AAG-1791 Fix ad sounds continue to play even after minimising the app
=> AAG-1791 Fix ad sounds continue to play even after minimising the app

app/src/main/res/values/strings.xml, docs/_data/toc.yml, superawesome-base/src/main/java/tv/superawesome/lib/sautils/SAUtils.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java
Again, MoPub is dead! We can finish removing all mentions.
=> Remove remaining MoPub mentions

.circleci/config.yml
Merging master into develop to test the semantic release. I think once this is merged the semantic release should work
=> Merging master into develop

.circleci/config.yml
Update the semantic release branch to `develop`
=> Update branch filter

app/build.gradle, app/src/androidTest/java/tv/superawesome/demoapp/VideoAdUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/util/VisibilityUtils.kt, app/src/androidTest/java/tv/superawesome/demoapp/util/WaitUtils.kt, app/src/main/java/tv/superawesome/demoapp/MainActivity.kt, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SADefaults.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoActivity.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/state/CloseButtonState.kt, superawesome-base/src/main/res/values/strings.xml
Add new functionality to display close button immediately for video ads
https://user-images.githubusercontent.com/4409219/174121084-27214fb2-1dfd-4fd6-ad8b-63d00bde8564.mp4
=> Display close button immediately for video ads

superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVersion.java
=> fix(): Close button to display immediately without a delay

superawesome-base/src/test/java/tv/superawesome/lib/saversion/TestSAVersion.kt
This PR is to trigger the `8.3.6` release
=> fix(): Version number store updates formatting

docs/_data/toc.yml, docs/_docs/examples.md, docs/_docs/initial-setup.md, docs/_docs/video-ads.md
This PR Updates the documentation for the options dictionary (for event tracking) and the immediate close button features.
=> Documentation updates

app/src/androidTest/java/tv/superawesome/demoapp/VideoAdUITest.kt, app/src/main/java/tv/superawesome/demoapp/MainActivity.kt
This PR updates the example app with a flat colour VPAID ad for smoke testing. Also updates the position for the existing video UI tests.
=> Placement updates for VPAID smoke test

superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/components/AdProcessor.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/datasources/NetworkDataSource.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/CreativeModels.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/VastModels.kt, superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/components/AdProcessorTest.kt, superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/testutil/FakeFactory.kt
fix(): Vast ads that are wrapped were not loading correctly. Fixes the recursive loading issue
=> fix(): Vast ads that are wrapped were not loading correctly

superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/player/VideoPlayerController.kt
This PR corrects the aspect ratio for video ads
=> chore(): fix video aspect ratio

superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/Constants.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/common/Config.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/dialog/CloseWarningDialog.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/SAVideoAd.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/VideoActivity.kt
This PR adds the ability to configure a video ad to show a warning dialog before closing
=> chore(): added an option to video ads to show a warning before closing

app/src/androidTest/java/tv/superawesome/demoapp/VideoAdUITest.kt, superawesome-base/src/main/resources/version.properties
=> release(): release 8.3.7

.circleci/config.yml, CHANGELOG.md
This PR swaps the order of tags and branches in the filter to see if it triggers `prep_deploy`
=> fix(): swapping filter order

CHANGELOG.md
This PR updates the changelog with the latest bug fixes
=> chore(): Update changelog with released fixes

.circleci/config.yml
Testing with `cat nextRelease`
=> fix(): testing with cat

.circleci/config.yml
=> fix(): testing directory

.circleci/config.yml
=> Testing cat output

.circleci/config.yml
=> fix(): cat test

app/src/androidTest/java/tv/superawesome/demoapp/BannerUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/InterstitialUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/VideoAdUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/interaction/SettingsInteraction.kt, app/src/main/java/tv/superawesome/demoapp/MainActivity.kt, app/src/main/java/tv/superawesome/demoapp/SettingsDialogFragment.kt, app/src/main/java/tv/superawesome/demoapp/model/SettingsData.kt, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values/strings.xml
chore(): adds new uitests for parental gate clicks
=> chore(): adds new uitests for parental gate clicks

app/src/androidTest/java/tv/superawesome/demoapp/BannerUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/InterstitialUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/VideoAdUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/interaction/ParentalGateInteraction.kt, app/src/androidTest/java/tv/superawesome/demoapp/util/ParentalGateUtil.kt, app/src/androidTest/java/tv/superawesome/demoapp/util/TextUtil.kt, app/src/androidTest/java/tv/superawesome/demoapp/util/WireMockHelper.kt
chore(): adds new uitests for parental gate events
=> chore(): adds new uitests for parental gate events

app/src/androidTest/java/tv/superawesome/demoapp/BannerUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/InterstitialUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/VideoAdUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/interaction/CommonInteraction.kt, app/src/androidTest/java/tv/superawesome/demoapp/util/AdapterUtil.kt, app/src/androidTest/resources/video_direct_success.json
chore(): add tests for on click to trigger webpage opening
=> chore(): add tests for on click to trigger webpage opening

app/src/androidTest/java/tv/superawesome/demoapp/InterstitialUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/interaction/CommonInteraction.kt, app/src/androidTest/java/tv/superawesome/demoapp/model/TestData.kt, app/src/main/java/tv/superawesome/demoapp/MainActivity.kt, app/src/main/java/tv/superawesome/demoapp/MainActivity2.kt, app/src/main/res/layout/activity_main_2.xml, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SADefaults.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAInterstitialAd.java, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/banner/BannerView.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/common/ViewableDetector.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/interstitial/InterstitialActivity.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/interstitial/SAInterstitialAd.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/managed/ManagedAdView.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/VideoEvents.kt
feat(): add immediately close button functionality to the interstitial ads
=> feat(): add immediately close button functionality to the interstitial ads

superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoActivity.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/videoPlayer/VideoPlayer.kt, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/videoPlayer/VideoPlayerController.kt
fix(): crash when the video is completed but later on clicked causing…
=> fix(): crash when the video is completed

superawesome-base/src/main/java/tv/superawesome/lib/sawebplayer/SAWebClient.java, superawesome-base/src/main/java/tv/superawesome/lib/sawebplayer/SAWebPlayer.java, superawesome-base/src/main/java/tv/superawesome/lib/sawebplayer/SAWebView.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAInterstitialAd.java, superawesome-base/src/main/resources/version.properties
fix(): when the `WebView` fails to load, then the error event for `adFailedToShow` is sent and the interstitial or banner ad is closed
=> fix(): when the `WebView` fails to load

docs/_docs/video-ads.md
=> chore(): update docs

.circleci/config.yml
This PR should fix the final step of the new release flow by pulling in the updated branch
=> fix(): CI semantic release fix

.circleci/config.yml
This PR should release version 8.5.1
=> chore(): release 8.5.1

app/src/main/java/tv/superawesome/demoapp/MainActivity.kt
This PR updates the example app with a new placement for Non-KSF VPAID testing
=> fix(): Added a new placement to support further VPAID testing

.github/PULL_REQUEST_TEMPLATE.md
=> NO-JIRA: Added PR Template

fastlane/Fastfile
NO-JIRA
Pointed fastlane to use a local fastfile instead of a remote one.
n/a
=> NO-JIRA: Updated fastlane path to use the local fastfile

superawesome-base/src/main/java/tv/superawesome/sdk/publisher/managed/SAManagedAdActivity.kt
[AAG-2735]
This PR adds an accessibility id to the project that is used here: https://github.com/SuperAwesomeLTD/sa-ad-smoke-test-sdk/pull/76
n/a
[AAG-2735]: https://superawesomeltd.atlassian.net/browse/AAG-2735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(): Added an accessibility id for the managed ad view

saunity/build.gradle, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityAwesomeAds.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityBannerAd.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityBumperPage.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityCallback.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityInterstitialAd.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityVersion.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityVideoAd.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/util/SAJsonUtil.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/util/SAScreenUtil.java, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/components/SdkInfo.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/AdModels.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/models/Platform.kt, superawesome-common/src/test/java/tv/superawesome/sdk/publisher/common/components/SdkInfoTest.kt
[AAG-2708]
Refactoring unity plugin code to use new common module
[AAG-2708]: https://superawesomeltd.atlassian.net/browse/AAG-2708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(): refactor android unity plugin to use the new common module

.circleci/config.yml
NO-JIRA
Cleaned up the CircleCI config to make it clearer
n/a
=> Tweaked CI config to clean things up

.circleci/config.yml
NO-JIRA
Correcting github token generation for semantic release.
n/a
=> NO-JIRA: Added missing github token generator

.circleci/config.yml
NO-JIRA
Update android access tokens on CI and context for build step
n/a
=> NO-JIRA: Update android access token

.circleci/config.yml
NO-JIRA
Corrected test run job on develop
n/a
=> NO-JIRA: Corrected test run job on develop

docs/pages/index.md
Correction for the android version info
=> [NO-JIRA] Update index.md

.github/CODEOWNERS
NO-JIRA
Updated the code owners file to the new team name
n/a
=> NO-JIRA: Updated the code owners file to the new team name

.circleci/config.yml
NO-JIRA
Updated CI script for release with known working changes from iOS
n/a
=> Updated CI script for release with known working changes from iOS

.circleci/config.yml
=> Fixed a missing github token step

.circleci/config.yml, superawesome-base/src/main/resources/version.properties
NO-JIRA
Reverted version and corrected circle ci script to run release tag phase
n/a
=> NO-JIRA: Reverted version and corrected circle ci script to run release tag phase

.circleci/config.yml, superawesome-base/src/main/resources/version.properties
NO-JIRA
Fixed semantic release issue
n/a
=> NO-JIRA: Fixed semantic release issue

build.gradle
no jira
chore(): revert espresso version to 3.4.0 as 3.5.1 was causing issues
n/a
=> chore(): revert espresso version to 3.4.0 as 3.5.1 was causing issues

saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobBannerAd.kt, saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobError.kt, saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobInterstitialAd.kt, saadmob/src/main/java/tv/superawesome/plugins/publisher/admob/SAAdMobRewardedAd.kt
[AAG-2859]
fix(): AdMob custom adapters so that the correct events are passed through the admob plugin from the awesome ads sdk
[AAG-2859]: https://superawesomeltd.atlassian.net/browse/AAG-2859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(): AdMob custom adapters

superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/AdVideoPlayerControllerView.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/SAVideoAd.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/VideoActivity.kt
NO-JIRA
Improved the syntax of some of the video files
n/a
=> NO-JIRA: Improved the syntax of some of the video files

saadmob/build.gradle, superawesome-base/build.gradle
[AAG-2885]
Rolled back core-ktx from 1.9.0 to 1.7.0 to bring it into line with the other modules.
n/a
[AAG-2885]: https://superawesomeltd.atlassian.net/browse/AAG-2885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Core-KTX): Rolled back core-ktx from 1.9.0 to 1.7.0 to bring it into line with the other modules.

saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityVideoAd.java
=> fix(): Video settings order

saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityVideoAd.java
=> fix(): unity video play order

gradle.properties
=> Commented out gradle vm properties

superawesome-base/build.gradle
NO-JIRA
Fixed a small kotlin version issue for the kotlin std lib in superawesomebase.gradle
n/a
=> fix(KotlinVersion): Fixed a small kotlin version issue for the kotlin std lib in superawesomebase.gradle

superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoClick.java
[AAG-2877]
fix(): Handles the case where the device doesn't have any browser to open web URLs
[AAG-2877]: https://superawesomeltd.atlassian.net/browse/AAG-2877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(): Handles the case where the device doesn't have any browser

saadmob/build.gradle, saunity/build.gradle, superawesome-base/build.gradle
NO-JIRA
Removed dependencies that cause conflicts when consuming the jar files in Unity.
n/a
=> fix(Dependencies): Removed dependencies that cause conflicts when consuming the jar files in Unity.

superawesome-base/src/main/resources/version.properties
NO-JIRA
Bumped version to: v8.5.5-RC
n/a
=> chore(): Bumped version to v8.5.5-RC

docs/pages/index.md
[AAG-2988]
Adds link to new documentation on homepage of existing Android docs. Eventually the whole docs folder here can be deleted as docs will now always live in the combined docs repo.
[AAG-2988]: https://superawesomeltd.atlassian.net/browse/AAG-2988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adds link to new documentation on homepage of existing Android docs.

app/src/androidTest/java/tv/superawesome/demoapp/VideoAdUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/interaction/CommonInteraction.kt, app/src/androidTest/java/tv/superawesome/demoapp/interaction/SettingsInteraction.kt, app/src/androidTest/java/tv/superawesome/demoapp/util/WaitUtils.kt, app/src/main/java/tv/superawesome/demoapp/main/MainActivity.kt, app/src/main/java/tv/superawesome/demoapp/model/SettingsData.kt, app/src/main/java/tv/superawesome/demoapp/settings/SettingsDialogFragment.kt, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoActivity.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/videoPlayer/VideoPlayerController.kt
[AAG-3009]
This update addresses instances where the adClosed event failed to transmit under specific conditions, while also preventing the occurrence of invalid state errors that are triggered by the Media Player.
n/a
[AAG-3009]: https://superawesomeltd.atlassian.net/browse/AAG-3009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Video Player): This update addresses instances where the adClosed event failed to transmit under specific conditions

superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoAd.java, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/managed/ManagedAdConfig.kt, superawesome-base/src/main/java/tv/superawesome/sdk/publisher/managed/SAManagedAdActivity.kt
[AAG-2889]
Added AutoCloseVideo and VideoCloseWarningDialog to Managed Ads (Interactive Video), UITests to follow in another PR.
https://user-images.githubusercontent.com/618350/228250602-217c75f8-8961-4af5-a25b-343b9f090a2c.mov
[AAG-2889]: https://superawesomeltd.atlassian.net/browse/AAG-2889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(InteractiveVideo): Added AutoCloseVideo and VideoCloseWarningDialog to Managed Ads (Interactive Video)

.circleci/config.yml
NO-JIRA
Added force commit for SA-Relase-Bot to bypass branch protection rules
n/a
=> Added force commit for SA-Relase-Bot to bypass branch protection rules

superawesome-base/src/main/resources/version.properties
NO-JIRA
Incremented the version number to 8.5.7
n/a
=> Incremented the version number to 8.5.7

.circleci/config.yml
NO-JIRA
Removed Force push from Semantic Release
n/a
=> Removed Force push from Semantic Release

saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityInterstitialAd.java, saunity/src/main/java/tv/superawesome/plugins/publisher/unity/SAUnityVideoAd.java
fix(Unity plugin): Adds missing settings to the unity plugin for Interstitial and Video ads
[AAG-3071]
[AAG-3071]: https://superawesomeltd.atlassian.net/browse/AAG-3071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Unity plugin): Adds missing settings to the unity plugin

app/src/androidTest/java/tv/superawesome/demoapp/VideoAdUITest.kt, app/src/androidTest/java/tv/superawesome/demoapp/rules/RetryTestRule.kt
[AAG-3027]
This PR adds a retrying test rule to reduce test failures. I'm also resetting the WireMock stubs before each test to clear off any per test stubs. 
This significantly improves the pass rate but I still see some failures which I think can be addressed by adding more stubs.
=> fix(UITesting): Adding a test rule to retry the tests in order to reduce flakiness

.github/PULL_REQUEST_TEMPLATE.md
NO-JIRA
Updated JIRA ticket Id for PR template to use AASDK
n/a
=> chore(): Updated JIRA ticket Id for PR template

superawesome-base/src/main/java/tv/superawesome/sdk/publisher/managed/SAManagedAdActivity.kt, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/managed/ManagedAdActivity.kt, superawesomecomposeexample/src/main/java/com/superawesome/composeexample/activities/FeatureDetailActivity.kt, superawesomecomposeexample/src/main/java/com/superawesome/composeexample/activities/FeaturesActivity.kt, superawesomecomposeexample/src/main/java/com/superawesome/composeexample/ui/theme/Theme.kt, superawesomecomposeexample/src/main/java/com/superawesome/composeexample/views/FeatureToggles.kt
[AASDK-446]
chore(Video): Add video leave warning to the common module
n/a
[AASDK-446]: https://superawesomeltd.atlassian.net/browse/AASDK-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(Video): Add video leave warning to the common module

.circleci/config.yml
[AASDK-465]
Added release and unit test step for the common module
n/a
[AASDK-465]: https://superawesomeltd.atlassian.net/browse/AASDK-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CI): Added release and unit test step for the common module

superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/managed/ManagedAdActivity.kt
[AASDK-455]
Changed how adEnded behaves to bring it into line with iOS and Base
n/a
[AASDK-455]: https://superawesomeltd.atlassian.net/browse/AASDK-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ManagedAd): Changed how adEnded behaves to bring it into line with iOS and Base

app/src/main/java/tv/superawesome/demoapp/main/MainActivity.kt, app/src/main/java/tv/superawesome/demoapp/settings/SettingsDialogFragment.kt
[[AASDK-476](https://superawesomeltd.atlassian.net/browse/AASDK-476)]
This PR adds content descriptions to the settings view for UI testing. iOS already has them in place. I'll create new binaries for iOS / Android for Sean when we've confirmed we've got everything we want to get into `develop` in. 
[AASDK-476]: https://superawesomeltd.atlassian.net/browse/AASDK-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(): Added content descriptions to the settings UI for the test app

superawesome-base/src/main/java/tv/superawesome/lib/saparentalgate/SAParentalGate.java
[[AASDK-448](https://superawesomeltd.atlassian.net/browse/AASDK-448)]
This PR adds handling of empty strings in the parental gate input
n/a
[AASDK-448]: https://superawesomeltd.atlassian.net/browse/AASDK-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ParentalGate): added validation for an empty string to the parental gate

.circleci/config.yml, superawesome-common/build.gradle
NO-JIRA
Fixed formatting in commands for publishing to docs site
n/a
=> fix(CI): Tweaks to the CI to fix issues around publishing

.circleci/config.yml
NO-JIRA
Corrected docs git push commands
n/a
=> chore(CI): Corrected docs git push commands

.circleci/config.yml, superawesome-common/src/main/resources/newVersion.properties
[AASDK-497]
Added missing CI code to fix version incrementing when releasing and set the Android Common module version to `9.0.2`.
n/a
[AASDK-497]: https://superawesomeltd.atlassian.net/browse/AASDK-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Common): Added missing CI code to fix version incrementing when releasing

superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAVideoAd.java, superawesome-common/src/main/java/tv/superawesome/sdk/publisher/common/ui/video/SAVideoAd.kt
[AASDK-502]
Added additional safe guards against empty Ads if the video file has not been downloaded 
n/a
[AASDK-502]: https://superawesomeltd.atlassian.net/browse/AASDK-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Video): Added additional safe guards against empty Ads if the video file has not been downloaded 
